[package]
name = "fdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
rusqlite = "0.26"
clap = { version = "3.1.2", features = ["derive"] }
